theme: null
title: Clifford William
tagline: Exploring the intersection of creativity and code.
author: Clifford William
email: ccliffordwilliam@gmail.com
description: >
  Welcome to my portfolio! I'm Clifford William, 
  a passionate full-stack developer crafting innovative web solutions. 
  Here, I share my projects and insights at the intersection of creativity and technology.
domain: cliffordwilliam.com
url: https://cliffordwilliam.com
date_format: "%b %-d, %Y"
excerpt_separator: "<!--more-->"
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
plugins:
  - jekyll-feed
  - jekyll-avatar
  - jekyll-seo-tag
sass:
  style: compressed
exclude:
  - todo.md
