theme: null
title: Clifford William
description: Bookmark this to keep an eye on my project updates!
domain: cliffordwilliam.com
url: https://cliffordwilliam.com
date_format: "%b %-d, %Y"
excerpt_separator: "<!--more-->"
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
plugins:
  - jekyll-feed
  - jekyll-avatar
  - jekyll-github-metadata
sass:
  style: compressed
exclude:
  - todo.md
