# https://pages.github.com/versions/
# GitHub Pages uses very old versions
# https://github.com/jekyll/minima/releases/tag/v2.5.1
theme: minima
title: Clifford William
description: Bookmark this to keep an eye on my project updates!
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
plugins:
  - jekyll-feed